# Generated by Django 5.0 on 2024-04-12 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('choices', models.JSONField()),
                ('answer', models.IntegerField()),
                ('created_by', models.CharField(default='Adithya', max_length=100)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('update_by', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
