# Generated by Django 5.0 on 2024-04-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsquestion',
            old_name='text',
            new_name='question',
        ),
    ]
