# Generated by Django 5.0 on 2024-04-13 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0003_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_register',
            name='e_mail',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_register',
            name='ph_no',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_register',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
